EC2 cleanup
bitovi/github-actions-commons pull request #22
Opened 2023-05-19 17:30 UTC by LeoDiazL

- docker compose down, delete and prune images, volumes, everything.
- unmount EFS, delete mount-point, compress app folder and remove it

2023-05-19 18:59 UTC, mickmcgrath13 approved these changes
LGTM! where's it tested?

2023-05-19 19:01 UTC, PhillypHenning requested changes

2023-05-19 19:32 UTC, LeoDiazL commented on operations/deployment/ansible/docker_cleanup/bitops.before-deploy.d/print-ansible-run.sh
> +#!/bin/bash
The shebang you mean ? or the echo's?
To make it easier to read the logs

2023-05-23 17:05 UTC, LeoDiazL commented
@mickmcgrath13 Testing done [here](https://github.com/bitovi/devops-training-ec2-gha-example/actions/runs/5059586687/jobs/9081335132)
Thought's about @mcascone comments?

2023-05-23 20:29 UTC, merged